version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: arrow
    versions:
    - "> 1.0.2, < 1.1"
  - dependency-name: twilio
    versions:
    - "> 6.51.1, < 7"
